# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 375f56ab6cba38adcf3894033b50b0d6ed14debda8cf1c5b84f47168d32ec207cbf2936ff6fb0a23ee0946f412d96ff1ad5bbaf4e48f39cb11d664f8834f2687

test:
  secret_key_base: ce915e66aade9b7af3a4af29f1af41951a7772a0a31fb68cd488f186261b716a8b27ea961616fb9ae8913732e3de144647d886e6005f96a44b3797e7acbea1b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
